 
############################################################
# Dockerfile to Deploy 
# '/var/lib/jenkins/workspace/com Build/target/calculator-1.0-SNAPSHOT.jar' 
# into 'anmol/ubuntu_18.04.3_lts-openjdk_1.8.0_242' Docker Image
############################################################

# Set the base image
FROM anmol/ubuntu_18.04.3_lts-openjdk_1.8.0_242

# File Author
MAINTAINER Anmol_Tuteja

# Set Working Directory
WORKDIR /usr/local

# Copies the files from the source on the host into the container’s set destination
ADD target/calculator-1.0-SNAPSHOT.jar .

# Default container command
ENTRYPOINT ["/usr/bin/java", "-cp", "calculator-1.0-SNAPSHOT.jar", "com/Calculator"]
